-- Script per creare la tabella ana_tipo_viaggi (PostgreSQL syntax per Npgsql)
-- Nota: I tipi Oracle (NUMBER, VARCHAR2) sono stati mappati ai tipi PostgreSQL equivalenti.

CREATE TABLE IF NOT EXISTS ana_tipo_viaggi (
    tipo_viaggi_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_viaggi_tipo CHAR(6) NOT NULL,
    tipo_viaggi_descrizione VARCHAR(100) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tipo_viaggi_tipo ON ana_tipo_viaggi (tipo_viaggi_tipo);
CREATE INDEX IF NOT EXISTS idx_tipo_viaggi_descrizione ON ana_tipo_viaggi (tipo_viaggi_descrizione);
