-- Script per creare la tabella ANA_TIPO_PARTECIPANTE (PostgreSQL syntax)
-- Mappatura tipi Oracle -> PostgreSQL:
-- NUMBER -> INTEGER
-- VARCHAR2 -> VARCHAR

CREATE TABLE IF NOT EXISTS ANA_TIPO_PARTECIPANTE (
    TIPO_PARTECIPANTE_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TIPO_PARTECIPANTE_DESCRIZIONE VARCHAR(100) NOT NULL,
    TIPO_PARTECIPANTE_DATI_MEZZO_OBB CHAR(1) NOT NULL DEFAULT 'N',
    CONSTRAINT chk_tipo_part_desc_not_null CHECK (TIPO_PARTECIPANTE_DESCRIZIONE IS NOT NULL),
    CONSTRAINT chk_tipo_part_id_not_null CHECK (TIPO_PARTECIPANTE_ID IS NOT NULL),
    CONSTRAINT chk_tipo_part_dati_mezzo CHECK (TIPO_PARTECIPANTE_DATI_MEZZO_OBB IN ('Y', 'N'))
);

-- Indice richiesto per DESCRIZIONE
CREATE INDEX IF NOT EXISTS idx_tipo_partecipante_descrizione ON ANA_TIPO_PARTECIPANTE (TIPO_PARTECIPANTE_DESCRIZIONE);

-- NOTA: Il trigger di INSERT "ANA_TIPO_PARTECIPANTE_TRG1" per la generazione dell'ID
-- è stato sostituito dalla clausola "GENERATED BY DEFAULT AS IDENTITY" definita nella tabella,
-- che è lo standard PostgreSQL per ottenere lo stesso risultato in modo più efficiente.

-- Funzione per il trigger di DELETE (Conversione di ANA_TIPO_PARTECIPANTE_TRG2)
CREATE OR REPLACE FUNCTION check_delete_ana_tipo_partecipante()
RETURNS TRIGGER AS $$
DECLARE
    v_count_clienti_viaggi INTEGER;
    v_error_msg VARCHAR(500);
BEGIN
    -- Controlla se la tabella MOV_CLIENTI_VIAGGI esiste prima di interrogarla
    -- Nota: Se la tabella referenziata non esiste ancora, questa query fallirà. 
    -- Si assume che MOV_CLIENTI_VIAGGI esista o verrà creata. 
    -- In PostgreSQL, è preferibile usare Foreign Keys per questo tipo di integrità.
    
    -- Verifica esistenza record correlati (simulazione referential integrity custom)
    BEGIN
        SELECT COUNT(*) 
        INTO v_count_clienti_viaggi 
        FROM MOV_CLIENTI_VIAGGI 
        WHERE TIPO_PARTECIPANTE_ID_FK = OLD.TIPO_PARTECIPANTE_ID;
    EXCEPTION
        WHEN undefined_table THEN
            -- Se la tabella non esiste, assumiamo 0 dipendenze
            v_count_clienti_viaggi := 0;
    END;
    
    IF v_count_clienti_viaggi > 0 THEN
        v_error_msg := 'Impossibile cancellare il tipo di partecipante "' || 
                      OLD.TIPO_PARTECIPANTE_DESCRIZIONE || '": ' ||
                      'è utilizzato da ' || v_count_clienti_viaggi || ' clienti iscritti a viaggi';
        
        -- RAISE EXCEPTION sostituisce RAISE_APPLICATION_ERROR
        RAISE EXCEPTION '%', v_error_msg USING ERRCODE = 'P0001'; -- P0001 = raise_exception
    END IF;

    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

-- Creazione del Trigger di DELETE
DROP TRIGGER IF EXISTS ANA_TIPO_PARTECIPANTE_TRG2 ON ANA_TIPO_PARTECIPANTE;

CREATE TRIGGER ANA_TIPO_PARTECIPANTE_TRG2
BEFORE DELETE ON ANA_TIPO_PARTECIPANTE
FOR EACH ROW
EXECUTE FUNCTION check_delete_ana_tipo_partecipante();
