-- Create table ANA_TIPO_ALLOGGIO
CREATE TABLE IF NOT EXISTS ana_tipo_alloggio (
    tipo_alloggio_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_alloggio_descrizione VARCHAR(100) NOT NULL UNIQUE,
    tipo_alloggio_numero_occupanti INTEGER NOT NULL DEFAULT 0 CHECK (tipo_alloggio_numero_occupanti >= 0 AND tipo_alloggio_numero_occupanti <= 6),
    tipo_alloggio_supplemento CHAR(1) NOT NULL DEFAULT 'N' CHECK (tipo_alloggio_supplemento IN ('Y', 'N'))
);
