-- Script per creare la tabella ana_tipo_mezzi (PostgreSQL syntax)
-- Traduzione da DDL Oracle

CREATE TABLE IF NOT EXISTS ana_tipo_mezzi (
    ana_tipo_mezzo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ana_tipo_mezzo_descrizione VARCHAR(100) NOT NULL,
    CONSTRAINT ana_tipo_mezzi_idx01 UNIQUE (ana_tipo_mezzo_descrizione)
);

-- Nota: Il trigger TRG1 (auto-increment) è sostituito da GENERATED BY DEFAULT AS IDENTITY
-- Nota: Il trigger TRG2 (controllo dipendenze) non è implementato qui.
--       In PostgreSQL si consiglia di usare FOREIGN KEY con ON DELETE RESTRICT sulla tabella figlia (ana_mezzi_modelli).
--       Se ana_mezzi_modelli verrà creata successivamente, dovrà includere:
--       CONSTRAINT fk_mezzi_modelli_tipo FOREIGN KEY (mezzo_modello_tipo_fk)
--       REFERENCES ana_tipo_mezzi (ana_tipo_mezzo_id) ON DELETE RESTRICT;
