-- =============================================================================
-- 580 — I prefissi telefonici internazionali diventano una tabella
-- =============================================================================
--
-- Deciso il 2026-09-04, durante i test del sito. Fino a qui il prefisso
-- internazionale non era un dato codificato da nessuna parte:
--
--   * nel GESTIONALE era un campo di TESTO LIBERO — si digitava qualunque cosa;
--   * nel SITO era una tendina di DIECI voci, tutte europee, scritte a mano in
--     Classi_Tabelle_Statiche/pref_tel_internazionali.py.
--
-- Le conseguenze erano gia' nei dati: un cliente con +27 (Sudafrica) o +34
-- (Spagna) arrivava al sito con il campo VUOTO, perche' quei prefissi la tendina
-- non li conosce — e salvando avrebbe perso il dato. E `+39` esiste in DUE
-- varianti, 431 volte e 7: con e senza spazi, perche' nessuno lo normalizzava.
--
-- La lista non e' un'opinione: e' lo standard ITU-E.164, e la sua sede e' il
-- database, dove la raggiungono entrambi i software.
--
-- I NOMI DEI PAESI NON SI RISCRIVONO: stanno gia' in eba_countries (249 paesi,
-- tutti con name_it). Qui c'e' solo la mappa paese → prefisso, verificata contro
-- quella tabella: 249 righe, nessun paese mancante, nessun duplicato.
-- =============================================================================

CREATE TABLE IF NOT EXISTS ana_tel_pref_int (
    pref_int_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Il prefisso come si compone, col +. E' questo che finisce in
    -- ana_clienti.cliente_preftelint, ed e' la ragione per cui non e' un intero.
    pref_int_codice  VARCHAR(6) NOT NULL,
    -- Il paese, come lo conosce eba_countries.
    pref_int_iso2    CHAR(2)    NOT NULL REFERENCES eba_countries(iso_alpha2),
    -- Un paese si puo' disattivare senza perdere lo storico di chi lo usa gia'.
    pref_int_attivo  BOOLEAN    NOT NULL DEFAULT TRUE,
    CONSTRAINT ana_tel_pref_int_uk UNIQUE (pref_int_iso2)
);

COMMENT ON TABLE ana_tel_pref_int IS
'Prefissi telefonici internazionali (ITU-E.164), uno per paese. I nomi dei paesi
stanno in eba_countries e non si duplicano qui. Usata dal gestionale e dal sito.';

-- Piu' paesi condividono lo stesso prefisso (+1 Stati Uniti e Canada, +7 Russia e
-- Kazakistan, +39 Italia e Vaticano): l'unicita' e' sul PAESE, non sul codice.
CREATE INDEX IF NOT EXISTS ana_tel_pref_int_codice_idx ON ana_tel_pref_int (pref_int_codice);


INSERT INTO ana_tel_pref_int (pref_int_iso2, pref_int_codice) VALUES
    ('AD', '+376'),
    ('AE', '+971'),
    ('AF', '+93'),
    ('AG', '+1268'),
    ('AI', '+1264'),
    ('AL', '+355'),
    ('AM', '+374'),
    ('AO', '+244'),
    ('AQ', '+672'),
    ('AR', '+54'),
    ('AS', '+1684'),
    ('AT', '+43'),
    ('AU', '+61'),
    ('AW', '+297'),
    ('AX', '+358'),
    ('AZ', '+994'),
    ('BA', '+387'),
    ('BB', '+1246'),
    ('BD', '+880'),
    ('BE', '+32'),
    ('BF', '+226'),
    ('BG', '+359'),
    ('BH', '+973'),
    ('BI', '+257'),
    ('BJ', '+229'),
    ('BL', '+590'),
    ('BM', '+1441'),
    ('BN', '+673'),
    ('BO', '+591'),
    ('BQ', '+599'),
    ('BR', '+55'),
    ('BS', '+1242'),
    ('BT', '+975'),
    ('BV', '+47'),
    ('BW', '+267'),
    ('BY', '+375'),
    ('BZ', '+501'),
    ('CA', '+1'),
    ('CC', '+61'),
    ('CD', '+243'),
    ('CF', '+236'),
    ('CG', '+242'),
    ('CH', '+41'),
    ('CI', '+225'),
    ('CK', '+682'),
    ('CL', '+56'),
    ('CM', '+237'),
    ('CN', '+86'),
    ('CO', '+57'),
    ('CR', '+506'),
    ('CU', '+53'),
    ('CV', '+238'),
    ('CW', '+599'),
    ('CX', '+61'),
    ('CY', '+357'),
    ('CZ', '+420'),
    ('DE', '+49'),
    ('DJ', '+253'),
    ('DK', '+45'),
    ('DM', '+1767'),
    ('DO', '+1809'),
    ('DZ', '+213'),
    ('EC', '+593'),
    ('EE', '+372'),
    ('EG', '+20'),
    ('EH', '+212'),
    ('ER', '+291'),
    ('ES', '+34'),
    ('ET', '+251'),
    ('FI', '+358'),
    ('FJ', '+679'),
    ('FK', '+500'),
    ('FM', '+691'),
    ('FO', '+298'),
    ('FR', '+33'),
    ('GA', '+241'),
    ('GB', '+44'),
    ('GD', '+1473'),
    ('GE', '+995'),
    ('GF', '+594'),
    ('GG', '+44'),
    ('GH', '+233'),
    ('GI', '+350'),
    ('GL', '+299'),
    ('GM', '+220'),
    ('GN', '+224'),
    ('GP', '+590'),
    ('GQ', '+240'),
    ('GR', '+30'),
    ('GS', '+500'),
    ('GT', '+502'),
    ('GU', '+1671'),
    ('GW', '+245'),
    ('GY', '+592'),
    ('HK', '+852'),
    ('HM', '+672'),
    ('HN', '+504'),
    ('HR', '+385'),
    ('HT', '+509'),
    ('HU', '+36'),
    ('ID', '+62'),
    ('IE', '+353'),
    ('IL', '+972'),
    ('IM', '+44'),
    ('IN', '+91'),
    ('IO', '+246'),
    ('IQ', '+964'),
    ('IR', '+98'),
    ('IS', '+354'),
    ('IT', '+39'),
    ('JE', '+44'),
    ('JM', '+1876'),
    ('JO', '+962'),
    ('JP', '+81'),
    ('KE', '+254'),
    ('KG', '+996'),
    ('KH', '+855'),
    ('KI', '+686'),
    ('KM', '+269'),
    ('KN', '+1869'),
    ('KP', '+850'),
    ('KR', '+82'),
    ('KW', '+965'),
    ('KY', '+1345'),
    ('KZ', '+7'),
    ('LA', '+856'),
    ('LB', '+961'),
    ('LC', '+1758'),
    ('LI', '+423'),
    ('LK', '+94'),
    ('LR', '+231'),
    ('LS', '+266'),
    ('LT', '+370'),
    ('LU', '+352'),
    ('LV', '+371'),
    ('LY', '+218'),
    ('MA', '+212'),
    ('MC', '+377'),
    ('MD', '+373'),
    ('ME', '+382'),
    ('MF', '+590'),
    ('MG', '+261'),
    ('MH', '+692'),
    ('MK', '+389'),
    ('ML', '+223'),
    ('MM', '+95'),
    ('MN', '+976'),
    ('MO', '+853'),
    ('MP', '+1670'),
    ('MQ', '+596'),
    ('MR', '+222'),
    ('MS', '+1664'),
    ('MT', '+356'),
    ('MU', '+230'),
    ('MV', '+960'),
    ('MW', '+265'),
    ('MX', '+52'),
    ('MY', '+60'),
    ('MZ', '+258'),
    ('NA', '+264'),
    ('NC', '+687'),
    ('NE', '+227'),
    ('NF', '+672'),
    ('NG', '+234'),
    ('NI', '+505'),
    ('NL', '+31'),
    ('NO', '+47'),
    ('NP', '+977'),
    ('NR', '+674'),
    ('NU', '+683'),
    ('NZ', '+64'),
    ('OM', '+968'),
    ('PA', '+507'),
    ('PE', '+51'),
    ('PF', '+689'),
    ('PG', '+675'),
    ('PH', '+63'),
    ('PK', '+92'),
    ('PL', '+48'),
    ('PM', '+508'),
    ('PN', '+64'),
    ('PR', '+1787'),
    ('PS', '+970'),
    ('PT', '+351'),
    ('PW', '+680'),
    ('PY', '+595'),
    ('QA', '+974'),
    ('RE', '+262'),
    ('RO', '+40'),
    ('RS', '+381'),
    ('RU', '+7'),
    ('RW', '+250'),
    ('SA', '+966'),
    ('SB', '+677'),
    ('SC', '+248'),
    ('SD', '+249'),
    ('SE', '+46'),
    ('SG', '+65'),
    ('SH', '+290'),
    ('SI', '+386'),
    ('SJ', '+47'),
    ('SK', '+421'),
    ('SL', '+232'),
    ('SM', '+378'),
    ('SN', '+221'),
    ('SO', '+252'),
    ('SR', '+597'),
    ('SS', '+211'),
    ('ST', '+239'),
    ('SV', '+503'),
    ('SX', '+1721'),
    ('SY', '+963'),
    ('SZ', '+268'),
    ('TC', '+1649'),
    ('TD', '+235'),
    ('TF', '+262'),
    ('TG', '+228'),
    ('TH', '+66'),
    ('TJ', '+992'),
    ('TK', '+690'),
    ('TL', '+670'),
    ('TM', '+993'),
    ('TN', '+216'),
    ('TO', '+676'),
    ('TR', '+90'),
    ('TT', '+1868'),
    ('TV', '+688'),
    ('TW', '+886'),
    ('TZ', '+255'),
    ('UA', '+380'),
    ('UG', '+256'),
    ('UM', '+1'),
    ('US', '+1'),
    ('UY', '+598'),
    ('UZ', '+998'),
    ('VA', '+39'),
    ('VC', '+1784'),
    ('VE', '+58'),
    ('VG', '+1284'),
    ('VI', '+1340'),
    ('VN', '+84'),
    ('VU', '+678'),
    ('WF', '+681'),
    ('WS', '+685'),
    ('YE', '+967'),
    ('YT', '+262'),
    ('ZA', '+27'),
    ('ZM', '+260'),
    ('ZW', '+263')
ON CONFLICT (pref_int_iso2) DO UPDATE SET pref_int_codice = EXCLUDED.pref_int_codice;


-- ---------------------------------------------------------------------------
-- La lettura, con il nome del paese preso da dove gia' vive.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_ana_tel_pref_int_get_all()
RETURNS TABLE(
    codice      VARCHAR,
    iso2        CHAR,
    paese       VARCHAR,
    descrizione TEXT
)
LANGUAGE sql
STABLE
AS $$
    SELECT p.pref_int_codice, p.pref_int_iso2, c.name_it,
           -- «+39 Italia»: si cerca sia digitando il numero sia il nome del paese,
           -- ed e' la stessa etichetta nei due software.
           (p.pref_int_codice || ' ' || c.name_it)::TEXT
    FROM ana_tel_pref_int p
    JOIN eba_countries c ON c.iso_alpha2 = p.pref_int_iso2
    WHERE p.pref_int_attivo
    -- L'Italia in cima: e' il caso di quasi tutti (431 clienti su 452). Poi in
    -- ordine alfabetico di paese, che e' come le persone li cercano.
    ORDER BY (p.pref_int_iso2 <> 'IT'), c.name_it;
$$;

COMMENT ON FUNCTION fn_ana_tel_pref_int_get_all() IS
'I prefissi telefonici selezionabili, con il nome italiano del paese. Italia in
testa, poi alfabetico. Unica fonte per il gestionale e per il sito di iscrizione.';


-- ---------------------------------------------------------------------------
-- I dati esistenti: gli spazi vanno via.
-- ---------------------------------------------------------------------------
-- Erano due valori diversi per la stessa cosa ('+39 ' e '+39'), e nessun
-- confronto poteva funzionare su entrambi.
UPDATE ana_clienti
   SET cliente_preftelint = btrim(cliente_preftelint)
 WHERE cliente_preftelint IS NOT NULL
   AND cliente_preftelint <> btrim(cliente_preftelint);

