-- =============================================================================
-- 599 — Il genere della sistemazione, e quali generi ammette un viaggio
-- =============================================================================
--
-- Nasce dall'analisi del 2026-09-05/06
-- (`Estensione Progetto WEB/Documenti/2026-09-05-Analisi_Scelta_Camere_Step5.md`).
--
-- ⚠️ Oggi non esiste NESSUN controllo incrociato fra il pernottamento previsto dal
-- viaggio e il tipo di sistemazione assegnato. Misurato su PROD: **17 assegnazioni
-- incoerenti** — camere d'albergo su viaggi con pernottamento `NESSUNO` — e nessuno
-- se n'era accorto, perche' non c'era niente che guardasse.
--
-- E le tende non si potevano nemmeno comporre: il sito salta il passo 5 quando
-- `con_albergo = 'N'`, quindi sui campi tendati la sistemazione non la chiede
-- nessuno. Sui PIRENEI del 19/08/2026 ci sono 12 iscritti e UNA riga di alloggio.
--
-- -----------------------------------------------------------------------------
-- PERCHE' UNA TABELLA E NON TRE VALORI SCRITTI NEL CODICE
-- -----------------------------------------------------------------------------
-- Domanda posta all'utente: «tre generi bastano?». Risposta: «no, un domani
-- potrebbero esserci condizioni di alloggio totalmente diverse che oggi non sono
-- state prese in considerazione» — bungalow, case mobili, rifugi, barche.
--
-- ⚠️ L'alternativa piu' ovvia — un booleano per genere sul pernottamento — e' gia'
-- FALLITA una volta: `ana_tipo_pernottamento_con_albergo` e' nato cosi', e il
-- giorno in cui sono comparse le tende non ha saputo dire niente. Si sarebbe
-- dovuto aggiungere `con_tenda`, poi `con_bungalow`, ognuno col suo controllo.
-- Con l'associazione, aggiungere un genere e' UNA RIGA e nessuna riga di codice.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. I generi
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ana_alloggio_generi (
    genere_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genere_codice      VARCHAR(20)  NOT NULL UNIQUE,
    genere_descrizione VARCHAR(60)  NOT NULL,
    genere_ordine      SMALLINT     NOT NULL DEFAULT 99,
    genere_attivo      BOOLEAN      NOT NULL DEFAULT TRUE
);

COMMENT ON TABLE ana_alloggio_generi IS
'Di che genere e'' una sistemazione: albergo, tenda, nessuna — e domani cio'' che servira''.
E'' una tabella e non un elenco scritto nel codice perche'' le condizioni di alloggio
cambiano: aggiungerne uno deve costare una riga, non una modifica al programma.';

COMMENT ON COLUMN ana_alloggio_generi.genere_codice IS
'Il codice con cui il programma riconosce il genere. ⚠️ NESSUNA ha un significato speciale:
vale su qualunque viaggio senza comparire fra i generi ammessi — «non mi serve una
sistemazione» e'' legittimo ovunque.';

INSERT INTO ana_alloggio_generi (genere_codice, genere_descrizione, genere_ordine) VALUES
    ('ALBERGO', 'Camera in struttura ricettiva', 1),
    ('TENDA',   'Tenda in campo tendato',        2),
    ('NESSUNA', 'Nessuna sistemazione',          9)
ON CONFLICT (genere_codice) DO UPDATE
    SET genere_descrizione = EXCLUDED.genere_descrizione,
        genere_ordine      = EXCLUDED.genere_ordine;


-- ---------------------------------------------------------------------------
-- 2. Ogni tipo di sistemazione ha il suo genere
-- ---------------------------------------------------------------------------
ALTER TABLE ana_tipo_alloggio
    ADD COLUMN IF NOT EXISTS genere_fk INTEGER REFERENCES ana_alloggio_generi(genere_id);

-- Si assegna dai dati che ci sono. ⚠️ Il riconoscimento per descrizione si fa UNA
-- volta sola, qui: da domani il genere e' un dato, non una parola da interpretare.
-- E' esattamente cio' che rende inutile il fragile `ILIKE '%TENDA%'` nel codice.
UPDATE ana_tipo_alloggio t SET genere_fk = g.genere_id
FROM ana_alloggio_generi g
WHERE t.genere_fk IS NULL
  AND g.genere_codice = CASE
        WHEN t.tipo_alloggio_numero_occupanti = 0            THEN 'NESSUNA'
        WHEN t.tipo_alloggio_descrizione ILIKE '%TENDA%'     THEN 'TENDA'
        ELSE 'ALBERGO'
      END;

-- Nessun tipo puo' restare senza genere: senza, la coerenza non e' verificabile.
ALTER TABLE ana_tipo_alloggio ALTER COLUMN genere_fk SET NOT NULL;

COMMENT ON COLUMN ana_tipo_alloggio.genere_fk IS
'Il genere di questa sistemazione. Prima si sarebbe dovuto dedurre dalla descrizione
(`ILIKE ''%TENDA%''`) o dagli identificativi scritti nel codice: due modi di smettere di
funzionare in silenzio il giorno in cui qualcuno rinomina una riga.';


-- ---------------------------------------------------------------------------
-- 3. Quali generi ammette ciascun tipo di pernottamento
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ana_tipo_pernottamento_generi (
    pernottamento_fk INTEGER NOT NULL REFERENCES ana_tipo_pernottamento(ana_tipo_pernottamento_id) ON DELETE CASCADE,
    genere_fk        INTEGER NOT NULL REFERENCES ana_alloggio_generi(genere_id),
    PRIMARY KEY (pernottamento_fk, genere_fk)
);

COMMENT ON TABLE ana_tipo_pernottamento_generi IS
'Quali generi di sistemazione ammette ciascun tipo di pernottamento. ⚠️ Molti a molti
perche'' il misto esiste: un viaggio puo'' prevedere albergo E tende. NESSUNA non compare
qui — vale sempre, ed e'' una regola, non una configurazione.';

-- Lo stato di oggi, dedotto dai nomi dei pernottamenti. Anche questo si fa una volta.
INSERT INTO ana_tipo_pernottamento_generi (pernottamento_fk, genere_fk)
SELECT p.ana_tipo_pernottamento_id, g.genere_id
FROM ana_tipo_pernottamento p
JOIN ana_alloggio_generi g ON
     (g.genere_codice = 'ALBERGO' AND p.ana_tipo_pernottamento_con_albergo = 'Y')
  OR (g.genere_codice = 'TENDA'   AND p.ana_tipo_pernottamento_descrizione ILIKE '%TENDAT%')
ON CONFLICT DO NOTHING;
